service_name: RssReader_v2
http_server_listen: 0.0.0.0:1323
cors:
  - http://127.0.0.1:8080
environment: local
mongo_db_config:
  url: mongodb://admin:admin@127.0.0.1:27017/db?authSource=admin
  database: rssreader
redis_config:
  addr: 127.0.0.1:6379
  password: '123456'