name: RssReader_Auto_Build_Test

on:
  push:
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14', '1.13' ]
    name: Go ${{ matrix.go }} build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Unit Test
        run: |
          cd src/apis
          go test

      - name: Build
        run: |
          cd src/main
          go build