name: RssReader_Auto_Build

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/RssReader_Backend_Build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.19' ]
    name: Go ${{ matrix.go }} build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Go Mod Tidy
        run: |
          cd src/
          go mod tidy

      - name: Build
        run: |
          cd src/
          go build

      - name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: src
          push: true
          tags: johnpoint/rssreader:latest
