name: RssReader_Web_Build

on:
  push:
    paths:
      - 'web/**'
      - '.github/workflows/RssReader_Web_Build.yml'

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node_version: [ 16.x,15.x,14.x,13.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies and Build
        run: |
          cd web
          yarn
          yarn build